server:
  port: 8000
  forward-headers-strategy: framework

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        # goods auth routing
        - id: goods-service
          uri: lb://GOODS-SERVICE
          predicates:
            - Path=/api/v1/goods/**
          filters:
            - JwtAuthenticationFilter

        # goods no auth routing
        - id: goods-service
          uri: lb://GOODS-SERVICE
          predicates:
            - Path=/api/v1/goods-n/**
          filters:


        # bid auth routing
        - id: bid-service
          uri: lb://BID-SERVICE
          predicates:
            - Path=/api/v1/bids/**
          filters:
            - JwtAuthenticationFilter

        # bid no auth routing
        - id: bid-service
          uri: lb://BID-SERVICE
          predicates:
            - Path=/api/v1/bids-n/**
          filters:

        # member auth routing
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/api/v1/users/**
          filters:
            - JwtAuthenticationFilter

        # member no auth routing
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/api/v1/users-n/**
          filters:

        # auth no auth routing
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth-n/**
          filters:

        # aggregation no auth routing
        - id: aggregation-service
          uri: lb://AGGREGATION-SERVICE
          predicates:
            - Path=/api/v1/aggregation-n/**
          filters:

        # aggregation no auth routing
        - id: aggregation-service
          uri: lb://AGGREGATION-SERVICE
          predicates:
            - Path=/api/v1/aggregation/**
          filters:
            - JwtAuthenticationFilter


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}/eureka/


jwt:
  key: ${JWT_SECRET_KEY}

springdoc:
  api-docs:
    path: /api/v3/api-docs
  swagger-ui:
    enabled: true
    path: /api/swagger-ui.html
    urls[0]:
      name: 인증 서비스
      url: http://3.35.70.208:8000/api/v1/auth-n/swagger/api-docs
    urls[1]:
      name: 회원 서비스
      url: http://3.35.70.208:8000/api/v1/users-n/swagger/api-docs
    urls[2]:
      name: 굿즈 서비스
      url: http://3.35.70.208:8000/api/v1/goods-n/swagger/api-docs
    urls[3]:
      name: 경매 서비스
      url: http://3.35.70.208:8000/api/v1/bids-n/swagger/api-docs
    urls[4]:
      name: 집계 서비스
      url: http://3.35.70.208:8000/api/v1/aggregation-n/swagger/api-docs
