server:
  port: 8000
  forward-headers-strategy: framework

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        # goods auth routing
        - id: goods-service
          uri: lb://GOODS-SERVICE
          predicates:
            - Path=/api/v1/goods/**
          filters:
            - JwtAuthenticationFilter

        # goods no auth routing
        - id: goods-service
          uri: lb://GOODS-SERVICE
          predicates:
            - Path=/api/v1/goods-n/**
          filters:


        # bid auth routing
        - id: bid-service
          uri: lb://BID-SERVICE
          predicates:
            - Path=/api/v1/bids/**
          filters:
            - JwtAuthenticationFilter

        # bid no auth routing
        - id: bid-service
          uri: lb://BID-SERVICE
          predicates:
            - Path=/api/v1/bids-n/**
          filters:

        # member auth routing
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/api/v1/users/**
          filters:
            - JwtAuthenticationFilter

        # member no auth routing
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/api/v1/users-n/**
          filters:


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}/eureka/


jwt:
  key: ${JWT_SECRET_KEY}

springdoc:
  api-docs:
    path: /api/v3/api-docs
  swagger-ui:
    enabled: true
    path: /api/swagger-ui.html
#    urls[0]:
#      name: 회원 서비스
#      url: http://goodsgoodsduck.shop/api/v1/users-n/swagger/api-docs
#    urls[1]:
#      name: 굿즈 서비스
#      url: http://goodsgoodsduck.shop/api/v1/goods-n/swagger/api-docs
#    urls[2]:
#      name: 경매 서비스
#      url: http://goodsgoodsduck.shop/api/v1/bids-n/swagger/api-docs
#    urls[0]:
#      name: 회원 서비스
#      url: http://3.35.70.208:9000/api/v1/users-n/swagger/api-docs
    urls[0]:
      name: 굿즈 서비스
#      url: http://3.35.70.208:9001/api/v1/goods-n/swagger/api-docs
      url: https://goodsgoodsduck.com/api/v1/goods-n/swagger/api-docs
    urls[1]:
      name: 경매 서비스
#      url: http://3.35.70.208:9002/api/v1/bids-n/swagger/api-docs
      url: https://goodsgoodsduck.com/api/v1/bids-n/swagger/api-docs